# Generated by Django 5.0.6 on 2024-07-19 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_projectpage_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='architectureimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/architecture'),
        ),
        migrations.AlterField(
            model_name='buildingimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/building'),
        ),
        migrations.AlterField(
            model_name='exteriorimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/exterior'),
        ),
        migrations.AlterField(
            model_name='interiorimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='projects/interior'),
        ),
    ]
