# Generated by Django 5.0.6 on 2024-07-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_alter_architectureimage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopupImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="popup_images/")),
                ("caption", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
