# Generated by Django 5.0.6 on 2024-08-09 06:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_popupimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactmessage",
            name="phone",
            field=models.CharField(
                max_length=10,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be exactly 10 digits.",
                        regex="^\\d{10}$",
                    )
                ],
            ),
        ),
    ]
