# Generated by Django 5.0.6 on 2026-06-30 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_packagedownload_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThumbnailImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/thumbnail')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnail_images', to='app.projectpage')),
            ],
        ),
    ]
